let words =[
           ["next",
            "short",
            "nice",
            "bottle",
            "full",
            "soda",
            "vast",
            "glue",
            "close",
            "hurry",
            "robin",
            "trace",
            "rock",
            "absent",
            "cover",
            "note",
            "burst",
            "relax",
            "group",
            "sad",
            "rob",
            "yell",
            "pop",
            "mix",
            "hot",
            "pin",
            "hill",
            "wiry",
            "dirt",
         ],
         [
            "paddle",
            "answer",
            "awesome",
            "distance",
            "fertile",
            "wakeful",
            "belief",
            "slippery",
            "bizarre",
            "learned",
            "vivacious",
            "grandmother",
            "illegal",
            "thirsty",
            "wholesale",
            "tenuous",
            "skillful",
            "deteriorate",
            "poised",
            "humorous",
            "scrape",
            "replace",
            "languid",
            "adjoining",
            "interesting",
            "stranger",
            "polite",
            "scissors",
            "brainy",
            "interrogation",  
        ],
        [
            "return;",
            "#include",
            "'helloworld'",
            "obj:1",
            "call()",
            "&lt;html&gt;",
            "not_easy",
            "more-dashes",
            "camelCase",
            "ASCII",
            "array[]",
            "printf('')",
            "&lt;/html&gt;",
            "^regex$",
            "System.out.println()",
        ],
        [
    
            
        ],
    ]
let score = 0;
let highscore = 0;
let pointer = 0;
let level = 0;
let current = words[level][pointer];
let input = document.querySelector("input");
let box = document.querySelector("scrollingwords");
let quaters = document.querySelectorAll('.quaters');
